### ISSUE TITLE
joblib.load(model.p) error

### ISSUE THREAD

**Issue by ralphpeterson** [dattalab/moseq2-model#9]
Just a caution for anyone doing analysis outside of your moseq2_model conda environment — be careful of what version of joblib you're running. Loading the model output failed when using joblib 0.8.4, but ran fine when updated to 0.11.

Example error:
```
>>>joblib.load(model.p)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-c9ba96e1f358> in <module>()
----> 1 joblib.load(fitfile)

/home/rep19/anaconda2/lib/python2.7/site-packages/joblib/numpy_pickle.pyc in load(filename, mmap_mode)
    423 
    424         try:
--> 425             obj = unpickler.load()
    426         finally:
    427             if hasattr(unpickler, 'file_handle'):

/home/rep19/anaconda2/lib/python2.7/pickle.pyc in load(self)
    862             while 1:
    863                 key = read(1)
--> 864                 dispatch[key](self)
    865         except _Stop, stopinst:
    866             return stopinst.value

/home/rep19/anaconda2/lib/python2.7/pickle.pyc in load_global(self)
   1094         module = self.readline()[:-1]
   1095         name = self.readline()[:-1]
-> 1096         klass = self.find_class(module, name)
   1097         self.append(klass)
   1098     dispatch[GLOBAL] = load_global

/home/rep19/anaconda2/lib/python2.7/pickle.pyc in find_class(self, module, name)
   1130         __import__(module)
   1131         mod = sys.modules[module]
-> 1132         klass = getattr(mod, name)
   1133         return klass
   1134 

AttributeError: 'module' object has no attribute 'NumpyArrayWrapper'
```
